[project]
name = "presence-qa-classifier"
version = "0.1.0"
description = "Train and deploy classifier that checks is there an answer on the question in the text."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []
