name: "boolq"
data_preparer: "boolq"
data_path: "data/boolq/boolq_3l_train_full.jsonl"
test_data_path: "data/boolq/boolq_3l_test_full.jsonl"
system_prompt_path: "data_system_prompts/boolq_system_prompt.txt"
